Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [3]:
import numpy as np

In [4]:
def matrix(vector,power):
  vec=np.array(vector)
  vec=vec.T
  new=np.zeros((len(vec),power+1))
  for i in range(power+1):
    new[:,i]=vec**i
  print(np.array(new))

In [5]:
matrix([2,0,4,1,1],2)

[[ 1.  2.  4.]
 [ 1.  0.  0.]
 [ 1.  4. 16.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [8]:
def moving_avg(ar,w):
  a=np.array(ar)
  i=0
  b=np.array(np.zeros((1,len(a)-w+1)))
  while i<(len(a)-w+1):
    b[0,i]=sum(a[i:i+w])/w
    i=i+1
  print(b)


In [9]:
moving_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

[[  5.           4.66666667   5.66666667   6.66666667   9.66666667
   28.66666667  49.33333333  72.66666667  84.          93.33333333
  116.33333333]]
